### PR TITLE
Add Leaflet.Fullscreen sample

### PR DESCRIPTION
**Pull request by sgrillon14**
image

### CODE REVIEW

**Comment by sgrillon14** [comment]
ready for use with docs in main page (add by @othiym21)

**Comment by reblace** [comment]
I'll take care of this soon. On vacation this week. Thanks for the contribution!

**Comment by reblace** [comment]
I need to change the base of this PR to go against develop. When I do, there are a bunch of conflicts.

The conflicts are a result of trying to merge together the changes made for the browser print and fullscreen examples. It looks like at one point the two PRs were on the same branch and then you separated and cleaned up each branch. The issue this has caused is there are conflicting deletes that are making Git think you moved a bunch of stuff.

Anyhow, can you fix the conflicts now that I've changed the base to develop? Thanks.

**Comment by sgrillon14** [comment]
I do not acces to "resolve conficts" button !!
image

**Comment by reblace** [comment]
You would need to merge my develop branch into your branch and resolve the conflicts there. Alternatively, you could create a clean branch off of my develop branch and copy over the relevant changes.

**Comment by reblace** [comment]
Added the fullscreen example manually. Thanks for the contribution!

**Pull request closed without merging**
