### PR TITLE
Add Leaflet.BrowserPrint sample

### PR DESCRIPTION
**Pull request by sgrillon14**

### CODE REVIEW

**Comment by sgrillon14** [comment]
online demo [here](https://igor-vladyka.github.io/leaflet.browser.print/)
capture d ecran 2018-02-03 a 17 59 56

**Comment by reblace** [comment]
I ran into an issue using v0.5.0 of leaflet.browser.print. It gives an npm error about the hash of the tgz file not matching.

As a result, I downgraded to 0.4.0 and updated a couple things to get it working with that version. If you find a solution (or if you cannot reproduce the issue, let me know.

**Comment by sgrillon14** [comment]
version v0.5.0 function well. version v0.5.0 was created precisely to work with angular (change L.browserPrint() by L.control.browserPrint())
[issue #15](https://github.com/Igor-Vladyka/leaflet.browser.print/issues/15)

I find error in my PR. I do not use yarn (so yarn.lock is wrong) **I put a fake hash of the tgz** file in my PR.

**Comment by reblace** [comment]
ok, yarn.lock was wrong. That's probably what caused it. I'll check it out.

**Comment by reblace** [comment]
Should be good now.

**Pull request merged**
